# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
a=[1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
np.array( [[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
np.arange(1,18,2).reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
np.random.rand(10)*10

array([5.21123512, 3.42271411, 8.41863607, 9.05091877, 0.87481072,
       9.42826073, 4.98176773, 9.20505637, 5.70994345, 1.70182866])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [8]:
b=np.array([1,2,3,4,5]).reshape(5,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [9]:
b.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [12]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(c[2], c[3], c[8])

2 3 8


Print alternate elements of that array

In [14]:
c[::2]

array([0, 2, 4, 6, 8])

Change last 3 elements into 100 using broadcasting and print

In [15]:
c[-3:]=100
c

array([  0,   1,   2,   3,   4,   5,   6, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [16]:
d=np.arange(25).reshape(5,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
d[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])