## Numpy

In [1]:
import numpy as np

In [7]:
a= np.array([1,2,3], dtype= complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
x= np.array([1,2,3], dtype=np.float)

In [5]:
x.dtype

dtype('float64')

## Indexing

In [8]:
arr1= np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr1[0]

1

In [10]:
arr1[9]

10

In [11]:
arr1[-1]

10

In [14]:
# slicing

arr1[1:5]

array([2, 3, 4, 5])

In [15]:
# [start, stop(not included), step]

In [16]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr1[0]=11
print(arr1)

[11  2  3  4  5  6  7  8  9 10]


In [19]:
# broadcasting
arr1[0:3]=0
arr1

array([ 0,  0,  0,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr1[0:3]=[1,2,3]
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr2= np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2[0]

array([1, 2, 3])

In [23]:
arr2[-1]

array([7, 8, 9])

In [24]:
arr2[0][1]  # this not reccomendable

2

In [25]:
arr2[0,1]

2

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# arr_name[row, column]
arr2[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [29]:
arr5= np.arange(9)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## conditional selection

In [35]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr1>2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
arr1[arr1>8]

array([ 9, 10])

In [39]:
arr1[(arr1 > 2) & (arr1 < 9)]

array([3, 4, 5, 6, 7, 8])

In [41]:
arr1[(arr1 == 2) | (arr1 < 9)]

array([1, 2, 3, 4, 5, 6, 7, 8])

## Operations

In [42]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr1+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
arr1-(arr1/2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [45]:
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
[1,2,3,4]*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [48]:
arr1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [50]:
# np.sqrt()
sqrt1= np.sqrt(np.array([1,4,9]))
sqrt1

array([1., 2., 3.])

In [51]:
# astype()
sqrt1.astype('int32')

array([1, 2, 3])

In [52]:
sqrt1.astype('str')

array(['1.0', '2.0', '3.0'], dtype='<U32')

In [53]:
np.exp(arr1) # e**value

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [54]:
np.sin(np.array([90,180]))

array([ 0.89399666, -0.80115264])

In [55]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr4= arr1*90
arr4

array([ 90, 180, 270, 360, 450, 540, 630, 720, 810, 900])

In [57]:
np.sin(arr4*np.pi/180)

array([ 1.0000000e+00,  1.2246468e-16, -1.0000000e+00, -2.4492936e-16,
        1.0000000e+00,  3.6739404e-16, -1.0000000e+00, -4.8985872e-16,
        1.0000000e+00,  6.1232340e-16])

In [58]:
np.sum(arr1)

55

In [59]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.multiply(arr2, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [61]:
np.dot(arr2, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [11]:
np.linalg.det(np.array([[5,2],[2,5]]))  # determinant

21.0

In [6]:
np.transpose(arr2)        # transpose the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])